# Generated by Django 4.2.13 on 2025-08-09 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredImage',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('file_ext', models.CharField(blank=True, max_length=16)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=64)),
                ('version_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reidresult',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('detecting', 'Detecting'), ('no_detection', 'No detection'), ('reidentifying', 'Re-Identifying'), ('completed', 'Completed'), ('error', 'Error')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='reidresult',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reid_results', to='api.storedimage'),
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snapshot', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tags', to='api.animal')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.storedimage')),
                ('reid_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='api.reidresult')),
            ],
            options={
                'indexes': [models.Index(fields=['image'], name='api_imageta_image_i_55fa1e_idx'), models.Index(fields=['animal'], name='api_imageta_animal__444925_idx'), models.Index(fields=['code_snapshot'], name='api_imageta_code_sn_4ced4c_idx')],
                'unique_together': {('image', 'animal')},
            },
        ),
    ]
