# Generated by Django 4.2.13 on 2025-08-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_storedimage_alter_reidresult_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedimage',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
