# Generated by Django 4.2.13 on 2025-08-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storedimage_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedimage',
            name='storage',
            field=models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], db_index=True, default='local', max_length=10),
        ),
    ]
