# Generated by Django 4.2.13 on 2025-08-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_storedimage_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedimage',
            name='storage_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
