"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── env setup ─────────────────────────────────────────────────────────────
env = environ.Env(
    DEBUG=(bool, True),
    POSTGRES_PORT=(int, 5432),
    DB_CONN_MAX_AGE=(int, 60),
    AWS_USE_S3=(bool, False),  # toggle S3 on/off via .env - disabled by default for local dev
     # ReID defaults
    REID_INDEX_DIM=(int, 128),           # SIFT descriptors are 128-D
    REID_INDEX_METRIC=(str, "euclidean"),
    REID_TOPK_PER_DESC=(int, 5),
    REID_MAX_DESCRIPTORS=(int, 500),

    # Detector defaults
    DETECTOR_DEVICE=(str, "cpu"),
    
    DETECT_SCORE_THRESH=(float, 0.5),
    DETECT_GRAYSCALE=(bool, True),
    DETECT_WARMUP_ITERS=(int, 0),
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

def env_path(key: str, default: str | None = None) -> str | None:
    """
    Read a path from env; trim quotes/whitespace; expand ~; make relative paths
    BASE_DIR-relative; return normalized absolute path (or default/None).
    """
    val = env.str(key, default=default or "")
    val = val.strip().strip('"').strip("'")
    if not val:
        return default
    val = os.path.expanduser(val)
    if not os.path.isabs(val):
        val = os.path.join(str(BASE_DIR), val)
    return os.path.normpath(val)

def _env_bool(name: str, default: bool = False) -> bool:
    return str(os.getenv(name, str(default))).strip().lower() in ("1","true","yes","on")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='dev-only-insecure-key')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', 
    'drf_yasg',# for DRF
    'api.apps.ApiConfig',
    'reid.apps.ReidConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Allow Next.js origin(s). Use schemes (http/https) and include ports.

CORS_ALLOWED_ORIGINS = env.list("DJANGO_CORS_ALLOWED_ORIGINS", default=[])
#CORS_ALLOWED_ORIGIN_REGEXES = env.list("DJANGO_CORS_ALLOWED_ORIGIN_REGEXES", default=[])
CORS_ALLOW_CREDENTIALS = env.bool("DJANGO_CORS_ALLOW_CREDENTIALS", default=False)

PRESIGN_EXPIRES = env.int("PRESIGN_EXPIRES", default=300)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.auth.APIKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "api.auth.HasAPIKey",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "api.auth.APIKeyRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "api_key": "60/min",  # tune
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ── database (DATABASE_URL preferred; else POSTGRES_* with sane defaults) ─
if env('DATABASE_URL', default=None):
    DATABASES = {'default': env.db('DATABASE_URL')}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':     env('POSTGRES_DB',      default='mydb'),
            'USER':     env('POSTGRES_USER',    default='myuser'),
            'PASSWORD': env('POSTGRES_PASSWORD',default='mypassword'),
            'HOST':     env('POSTGRES_HOST',    default='localhost'),
            'PORT':     env('POSTGRES_PORT',    default=5432),
            'CONN_MAX_AGE': env('DB_CONN_MAX_AGE'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── Celery / Redis ────────────────────────────────────────────────────────
CELERY_BROKER_URL      = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND  = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT  = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE        = TIME_ZONE

AWS_USE_S3 = env.bool("AWS_USE_S3", default=False)

# ── S3 storage (enabled only if AWS_USE_S3=True and bucket set) ───────────
if _env_bool('AWS_USE_S3') and env('AWS_STORAGE_BUCKET_NAME', default=None):
    INSTALLED_APPS += ['storages']
    AWS_ACCESS_KEY_ID       = env('AWS_ACCESS_KEY_ID', default=None)
    AWS_SECRET_ACCESS_KEY   = env('AWS_SECRET_ACCESS_KEY', default=None)
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME      = env('AWS_S3_REGION_NAME', default='ap-southeast-2')
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE  = "virtual"
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {"ServerSideEncryption": "AES256"}
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL', default=None)  # for LocalStack
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
else:
    # Fallback to local file storage when S3 is disabled
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# --- ReID (descriptor-level Annoy index) ---
REID_INDEX_PATH      = env.str("REID_INDEX_PATH", None)
REID_META_PATH       = env.str("REID_META_PATH", None)
REID_INDEX_DIM       = env.int("REID_INDEX_DIM", 128)
REID_INDEX_METRIC    = env.str("REID_INDEX_METRIC", "euclidean")
REID_FLIP_QUERY      = env.bool("REID_FLIP_QUERY", False)
REID_IMG_WIDTH       = env.int("REID_IMG_WIDTH", 256)
REID_MAX_KPTS        = env.int("REID_MAX_KPTS", 85)
REID_USE_CLAHE       = env.bool("REID_USE_CLAHE", True)
REID_TOPK_PER_DESC   = env.int("REID_TOPK_PER_DESC", 11)
REID_ANNOY_SEARCH_K  = env.int("REID_ANNOY_SEARCH_K", None)
REID_MASKS_ROOT      = env.str("REID_MASKS_ROOT", None)


# --- new for reid2 ---
# Used when REID_ANNOY_SEARCH_K == 0: search_k = n_items * REID_SEARCH_K_MULT
REID_SEARCH_K_MULT        = env.float("REID_SEARCH_K_MULT",        default=32.0)

# Cap matches counted per gallery image (prevents one photo dominating)
REID_PER_IMAGE_MATCH_CAP  = env.int("REID_PER_IMAGE_MATCH_CAP",    default=30)

# Rank weighting (1/rank) on neighbor lists
REID_USE_RANK_WEIGHT      = env.bool("REID_USE_RANK_WEIGHT",       default=True)

# Balance IDs by their gallery size (score /= #images for that ID)
REID_PER_ID_NORMALIZE     = env.bool("REID_PER_ID_NORMALIZE",      default=False)

# Optional: force engine selection in the Celery task ("" → auto, prefers reid2)
REID_IMPLEMENTATION       = env.str("REID_IMPLEMENTATION",         default="")

# Optional: force engine (otherwise reid2 is chosen when present)
REID_IMPLEMENTATION = os.getenv("REID_IMPLEMENTATION", "")  # "", "reid2", "reid1", "legacy"


# Optional: auto-assign threshold for predicted_animal (if you added that patch)
REID_ASSIGN_THRESHOLD = env.float("REID_ASSIGN_THRESHOLD", default=0.35)
REID_ALLOW_NUMERIC_PK_MATCH = env.bool("REID_ALLOW_NUMERIC_PK_MATCH", default=False)

DETECTOR_CHECKPOINT = env('DETECTOR_CHECKPOINT', default=None)  # path to .pt/.pth (relative to BASE_DIR or absolute)
DETECTOR_DEVICE     = env('DETECTOR_DEVICE', default='cpu')  

DETECT_SCORE_THRESH = env.float("DETECT_SCORE_THRESH")
DETECT_GRAYSCALE    = env.bool("DETECT_GRAYSCALE")
DETECT_WARMUP_ITERS = env.int("DETECT_WARMUP_ITERS")

# ── File Processing & Cleanup ─────────────────────────────────────────────
REID_TEMP_DIR = env('REID_TEMP_DIR', default=None)  # Custom temp dir, or use system default
REID_CLEANUP_INTERVAL = env.int('REID_CLEANUP_INTERVAL', default=3600)  # Cleanup every hour (seconds)


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGGING = {
  "version": 1,
  "disable_existing_loggers": False,
  "handlers": {
    "console": {"class": "logging.StreamHandler"}
  },
  "loggers": {
    "celery": {"handlers": ["console"], "level": "DEBUG"},
    "api.tasks": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
  }
}